# File is automatically loaded on applicaiton startup.
#
# Properties are used by @ConfigurationProperties defined throughout Spring Boot.

server:
   port: 8090

spring.datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:bootexample;MODE=MySQL
